### ISSUE TITLE
[Question] What is the license of PRVHASH algorithm (not the code in this repository)?

### ISSUE THREAD

**Issue by alpominth** [avaneev/prvhash#7]
Chacha20 is a stream cipher with a public domain license, but many implementations of it in Github have their own licenses such as MIT or GPL.

There is  also this statement in the repository:

`"PRVHASH "computer program" authorship and copyright were registered at the [Russian Patent Office](https://rospatent.gov.ru/en), under reg.numbers 2020661136, 2020666287, 2021615385, 2021668070, 2022612987 (searchable via [fips.ru](https://new.fips.ru/en/)). Please note that these are not "invention patents"; the registrations assure you that the author has the required rights to grant the software license to you."`

I'm little confused about the PRVHASH license. What is the license of PRVHASH itself (not the code in this repository)? It it MIT too?

@avaneev 
I mailed you about this question but I deleted a list of messages by accident and maybe the reply was gone.

Thanks.

**Comment by avaneev** [comment]
All available prvhash code is under MIT license.

**Comment by avaneev** [comment]
I'll also add that the "public domain" licenses may not be enforcable in all countries, until author's death. MIT license is a better option for such licensing.
